# -*- coding: utf-8 -*-
"""Customer_Retail_ML_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sZgrzLMhYeRPkktbhpln5CMAWcPbDq53
"""

#CSV File Upload
from google.colab import files
uploaded = files.upload()

#Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score, confusion_matrix

#Load Dataset
df = pd.read_csv("customer_retail csv file (1).csv")

df.head()

#Select Required Columns
df = df[['Quantity', 'UnitPrice', 'Country']]

df.head()

#Handle Missing Values
df.isnull().sum()

#Remove missing values
df = df.dropna()

#Encode Country Column
encoder = LabelEncoder()

df['Country'] = encoder.fit_transform(df['Country'])

df.head()

#Create Target Column
df['Target'] = np.where(df['Quantity'] > 10, 1, 0)

df.head()

#Define Features and Target
X = df[['Quantity', 'UnitPrice', 'Country']]

y = df['Target']

#Split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

#Logistic Regression
log_model = LogisticRegression()

log_model.fit(X_train, y_train)

log_pred = log_model.predict(X_test)

log_acc = accuracy_score(y_test, log_pred)

print("Logistic Regression Accuracy:", log_acc)

print(confusion_matrix(y_test, log_pred))

#Decision Tree
dt_model = DecisionTreeClassifier()

dt_model.fit(X_train, y_train)

dt_pred = dt_model.predict(X_test)

dt_acc = accuracy_score(y_test, dt_pred)

print("Decision Tree Accuracy:", dt_acc)

print(confusion_matrix(y_test, dt_pred))

#KNN Model
knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X_train, y_train)

knn_pred = knn_model.predict(X_test)

knn_acc = accuracy_score(y_test, knn_pred)

print("KNN Accuracy:", knn_acc)

print(confusion_matrix(y_test, knn_pred))

#Customer Distribution Graph
df['Country'].value_counts().head(10).plot(kind='bar')

plt.title("Customer Distribution")

plt.xlabel("Country")

plt.ylabel("Count")

plt.show()

#Accuracy Comparison Graph
models = ['Logistic Regression', 'Decision Tree', 'KNN']

accuracies = [log_acc, dt_acc, knn_acc]

plt.bar(models, accuracies)

plt.title("Model Accuracy Comparison")

plt.ylabel("Accuracy")

plt.show()